version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sauron-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    network_mode: host

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: sauron-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    network_mode: host
